# Generated by Django 3.1.5 on 2022-04-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0002_drawing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='title',
            new_name='drawtitle',
        ),
    ]
